name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and NPM dependencies based on the package-lock.json file.

inputs:
  node-version:
    description: NodesJS version to uses
    default: 20.x
    required: true
  working-dir:
    description: The working directory of the applccation
    default: .
    required: false
  target-env:
    description: '"dev" or "prod". Controls whether dev dependencies are installed'
    default: dev
    required: true

runs:
  using: composite
  steps: 
    - name: Setup NodeJS version ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-dir }}/node_modules
        key: node-modules-${{ hashFiles(format('{0}/{1}', inputs.working-dir, 'package-lock.json')) }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: ${{ inputs.target-env != 'dev' && 'npm ci' || 'npm ci --omit-dev' }}
      shell: bash  # alway required when using custom action
      working-directory: ${{ inputs.working-dir }}
  