name: 05 - 1 - Event Filters and Activity Types

on: 
    pull_request:
        types: 
            - opened
            - synchronize
        branches:
            - talent
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              run: echo 'Running whenever a PR is opened or synchronized AND base branch is main'