name: 05 - 2 - Event Filters and Activity Types

on: 
    pull_request:
        types: 
            - closed
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              run: echo 'Running whenever a PR is closed'