name: 10 - Controlling Execution Workflow


on: 
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                description: Whether the unit test will pass or fail
                default: true

jobs:
    # lint-build and unit-test are independent(nondependent) --> runs in parallel 
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: Lint and Build
              run: echo "Linting and building project"
    unit-test:
        runs-on: ubuntu-latest
        continue-on-error: true 
        steps:
            - name: Running Unit Tests
              run: echo "Running tests ..."
            - name: Failing test
              if: ${{ !inputs.pass-unit-tests }}
              run: exit 1
    deploy-nonprod:
        runs-on: ubuntu-latest
        needs: 
            - lint-build
            - unit-test
        steps:
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod..."

    # Both e2e-tests and load-tests are dependent on deploy-nonprod --> both are non dependent to each other 
    e2e-tests:
        runs-on: ubuntu-latest
        needs: deploy-nonprod
        steps:
            - name: Running E2E tests
              run: echo "Running E2E tests..."
    load-tests:
        runs-on: ubuntu-latest
        needs: 
            - deploy-nonprod
        steps:
            - name: Running load tests
              run: echo "Running load tests..."

    # Deploy to prod job is dependent on e2e-test and load-test
    deploy-prod:
        runs-on: ubuntu-latest
        needs:
            - e2e-tests
            - load-tests
        steps:
            - name: Deploy to prod
              run: echo "Deploying to prod..."